//HintName: Sample.Nested.Deep.Outer.Machine.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample.Nested.Deep
{
    public partial class Outer
    {
        internal static partial class Machine
        {
            public enum State
            {
                A,
                B,
            }
            
            public enum Trigger
            {
                Go,
            }
            
            public readonly struct TriggerArgs
            {
                private readonly int _kind;
                
                private TriggerArgs(int kind)
                {
                    _kind = kind;
                }
                
                public static TriggerArgs ForGo() => new TriggerArgs(1);
                
                public object? Value => _kind switch
                {
                    1 => null,
                    _ => null,
                };
                
                public bool HasValue => _kind != 0;
                
                public override string? ToString() => _kind switch
                {
                    1 => null,
                    _ => null,
                };
            }
            
            protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor>
            {
            }
            
            protected interface IStateConfigurator : global::Nalu.SharpState.IStateLifecycleFluent<IStateConfigurator, global::Sample.Nested.Deep.Ctx>, IStateConfiguration
            {
                /// <summary>
                /// Configures what happens when <see cref="IActor.Go()"/> is invoked.
                /// </summary>
                /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.IStateTriggerBuilder{global::Sample.Nested.Deep.Ctx, State, IActor}"/> used by <see cref="IActor.Go()"/>.</param>
                /// <returns>The same configurator for chaining.</returns>
                IStateConfigurator OnGo(Action<global::Nalu.SharpState.IStateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State, IActor>> configure);
            }
            
            /// <summary>
            /// <see cref="global::Sample.Nested.Deep.Outer.Machine"/> runtime actor.
            /// </summary>
            public interface IActor
            {
                /// <summary>
                /// Gets the current leaf <see cref="State"/>.
                /// </summary>
                State CurrentState { get; }
                
                /// <summary>
                /// Gets the shared context passed to guards, actions, and reactions.
                /// </summary>
                global::Sample.Nested.Deep.Ctx Context { get; }
                
                /// <summary>
                /// Gets or sets the callback invoked when a trigger has no matching transition.
                /// </summary>
                global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled { get; set; }
                
                /// <summary>
                /// Raised after a transition commits and changes the current state.
                /// </summary>
                event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged;
                
                /// <summary>
                /// Raised when a background reaction scheduled by <c>ReactAsync(...)</c> fails.
                /// </summary>
                event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed;
                
                /// <summary>
                /// Determines whether the current leaf equals <paramref name="state"/> or is contained by it.
                /// </summary>
                /// <param name="state">The state to test against the current hierarchy.</param>
                /// <returns><c>true</c> when the actor is currently in <paramref name="state"/>; otherwise <c>false</c>.</returns>
                bool IsIn(State state);
                
                /// <summary>
                /// Determines whether <see cref="IActor.Go()"/> can be invoked from the current state.
                /// </summary>
                /// <returns><c>true</c> when a matching transition exists; otherwise <c>false</c>.</returns>
                bool CanGo();
                
                /// <summary>
                /// Fires <see cref="Trigger.Go"/> from the current state.
                /// </summary>
                void Go();
            }
            
            static partial void Go()
            {
            }
            
            static Machine()
            {
                #nullable disable
                Go();
                #nullable enable
            }
            
            /// <summary>
            /// Factory delegate that creates a new <see cref="IActor"/> at a given <see cref="State"/>, bound to this generated state machine definition.
            /// Useful for dependency injection and unit tests.
            /// </summary>
            /// <param name="context">The shared <see cref="global::Sample.Nested.Deep.Ctx"/> passed to guards, actions, and reactions.</param>
            /// <param name="serviceProviderResolver">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>
            /// <param name="state">The starting state. Composite states resolve to their initial leaf.</param>
            /// <returns>A new <see cref="IActor"/> instance.</returns>
            public delegate IActor CreateActorWithStateFactory(global::Sample.Nested.Deep.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state);
            
            /// <summary>
            /// Factory delegate that creates a new <see cref="IActor"/> starting at <see cref="GetInitialState()"/>, bound to this generated state machine definition.
            /// Useful for dependency injection and unit tests.
            /// </summary>
            /// <param name="context">The shared <see cref="global::Sample.Nested.Deep.Ctx"/> passed to guards, actions, and reactions.</param>
            /// <param name="serviceProviderResolver">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>
            /// <returns>A new <see cref="IActor"/> instance.</returns>
            public delegate IActor CreateActorFactory(global::Sample.Nested.Deep.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver);
            
            private static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
            
            private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor> _definition = BuildDefinition();
            
            private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor> BuildDefinition()
            {
                var map = new global::Nalu.SharpState.InternalEnumMap<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor>>();
                {
                    var c = (GeneratedStateConfigurator)A;
                    map[State.A] = c;
                }
                {
                    var c = (GeneratedStateConfigurator)B;
                    map[State.B] = c;
                }
                return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor>(map);
            }
            
            /// <summary>
            /// Gets the initial root <see cref="State"/> of this generated state machine.
            /// </summary>
            /// <returns>The initial root <see cref="State"/>.</returns>
            public static State GetInitialState() => State.A;
            
            /// <summary>
            /// Renders this generated state machine as a Graphviz DOT graph.
            /// </summary>
            /// <returns>The DOT source representing the machine graph.</returns>
            public static string ToDot() => global::Nalu.SharpState.StateMachineExporter.ToDot(_definition, GetInitialState(), "Machine");
            
            /// <summary>
            /// Renders this generated state machine as a Mermaid state diagram.
            /// </summary>
            /// <returns>The Mermaid state diagram source representing the machine graph.</returns>
            public static string ToMermaid() => global::Nalu.SharpState.StateMachineExporter.ToMermaid(_definition, GetInitialState(), "Machine");
            
            /// <summary>
            /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
            /// </summary>
            /// <param name="context">The shared <see cref="global::Sample.Nested.Deep.Ctx"/> passed to guards, actions, and reactions.</param>
            /// <param name="serviceProviderResolver">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>
            /// <param name="state">The starting state. Composite states resolve to their initial leaf.</param>
            /// <returns>A new <see cref="IActor"/> instance.</returns>
            public static IActor CreateActorWithState(global::Sample.Nested.Deep.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state) => new Actor(_definition, state, context, serviceProviderResolver);
            
            /// <summary>
            /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
            /// </summary>
            /// <param name="context">The shared <see cref="global::Sample.Nested.Deep.Ctx"/> used to create an actor starting from <see cref="GetInitialState()"/>.</param>
            /// <param name="serviceProviderResolver">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>
            /// <returns>A new <see cref="IActor"/> instance at the machine's initial state.</returns>
            public static IActor CreateActor(global::Sample.Nested.Deep.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver) => CreateActorWithState(context, serviceProviderResolver, GetInitialState());
            
            private sealed class Actor : IActor
            {
                private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor> _engine;
                
                internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor> definition, State currentState, global::Sample.Nested.Deep.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver)
                {
                    _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor>(definition, currentState, context, this, serviceProviderResolver);
                }
                
                public State CurrentState => _engine.CurrentState;
                
                public global::Sample.Nested.Deep.Ctx Context => _engine.Context;
                
                public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled
                {
                    get => _engine.OnUnhandled;
                    set => _engine.OnUnhandled = value;
                }
                
                public event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged
                {
                    add => _engine.StateChanged += value;
                    remove => _engine.StateChanged -= value;
                }
                
                public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed
                {
                    add => _engine.ReactionFailed += value;
                    remove => _engine.ReactionFailed -= value;
                }
                
                public bool IsIn(State state) => _engine.IsIn(state);
                
                public bool CanGo() => _engine.CanFire(Trigger.Go, TriggerArgs.ForGo());
                
                public void Go() => _engine.Fire(Trigger.Go, TriggerArgs.ForGo());
            }
            
            private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, Trigger, IActor>, IStateConfigurator
            {
                internal void ApplyParent(State parent) => SetParent(parent);
                
                internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
                
                public IStateConfigurator OnGo(Action<global::Nalu.SharpState.IStateTriggerBuilder<global::Sample.Nested.Deep.Ctx, State, IActor>> configure)
                {
                    var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Nested.Deep.Ctx, TriggerArgs, State, IActor>();
                    configure(builder);
                    builder.Validate();
                    AddTransitions(Trigger.Go, builder.BuildTransitions());
                    return this;
                }
            }
        }
    }
}
