//HintName: Sample.Documented.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample
{
    public static partial class Documented
    {
        public enum State
        {
            /// <inheritdoc cref="P:Sample.Documented.Closed"/>
            Closed,
            Opened,
        }
        
        public enum Trigger
        {
            /// <inheritdoc cref="M:Sample.Documented.Open(System.String)"/>
            Open,
            Close,
        }
        
        public readonly struct OpenArgs
        {
            public readonly string Reason;
            
            public OpenArgs(string reason)
            {
                Reason = reason;
            }
            
            public void Deconstruct(out string reason)
            {
                reason = Reason;
            }
        }
        
        public readonly struct TriggerArgs
        {
            private readonly int _kind;
            private readonly OpenArgs _value1;
            
            private TriggerArgs(int kind)
            {
                _kind = kind;
            }
            
            public TriggerArgs(OpenArgs value)
            {
                _kind = 1;
                _value1 = value;
            }
            
            public static TriggerArgs ForClose() => new TriggerArgs(2);
            
            public object? Value => _kind switch
            {
                1 => _value1,
                2 => null,
                _ => null,
            };
            
            public bool HasValue => _kind != 0;
            
            public bool TryGetValue(out OpenArgs value)
            {
                value = _kind == 1 ? _value1 : default;
                return _kind == 1;
            }
            
            public override string? ToString() => _kind switch
            {
                1 => _value1.ToString(),
                2 => null,
                _ => null,
            };
        }
        
        protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>
        {
        }
        
        protected interface IStateConfigurator : global::Nalu.SharpState.IStateLifecycleFluent<IStateConfigurator, global::Sample.Ctx>, IStateConfiguration
        {
            /// <summary>
            /// Configures what happens when <see cref="IActor.Open(string)"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.IStateTriggerArgsBuilder{global::Sample.Ctx, State, IActor, OpenArgs}"/> used by <see cref="IActor.Open(string)"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnOpen(Action<global::Nalu.SharpState.IStateTriggerArgsBuilder<global::Sample.Ctx, State, IActor, OpenArgs>> configure);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.Close()"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.IStateTriggerBuilder{global::Sample.Ctx, State, IActor}"/> used by <see cref="IActor.Close()"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnClose(Action<global::Nalu.SharpState.IStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure);
        }
        
        /// <summary>
        /// <see cref="global::Sample.Documented"/> runtime actor.
        /// </summary>
        public interface IActor
        {
            /// <summary>
            /// Gets the current leaf <see cref="State"/>.
            /// </summary>
            State CurrentState { get; }
            
            /// <summary>
            /// Gets the shared context passed to guards, actions, and reactions.
            /// </summary>
            global::Sample.Ctx Context { get; }
            
            /// <summary>
            /// Gets or sets the callback invoked when a trigger has no matching transition.
            /// </summary>
            global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled { get; set; }
            
            /// <summary>
            /// Raised after a transition commits and changes the current state.
            /// </summary>
            event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged;
            
            /// <summary>
            /// Raised when a background reaction scheduled by <c>ReactAsync(...)</c> fails.
            /// </summary>
            event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed;
            
            /// <summary>
            /// Determines whether the current leaf equals <paramref name="state"/> or is contained by it.
            /// </summary>
            /// <param name="state">The state to test against the current hierarchy.</param>
            /// <returns><c>true</c> when the actor is currently in <paramref name="state"/>; otherwise <c>false</c>.</returns>
            bool IsIn(State state);
            
            /// <summary>
            /// Determines whether <see cref="IActor.Open(string)"/> can be invoked from the current state.
            /// </summary>
            /// <param name="reason">The value to test with the trigger.</param>
            /// <returns><c>true</c> when a matching transition exists; otherwise <c>false</c>.</returns>
            bool CanOpen(string reason);
            
            /// <inheritdoc cref="M:Sample.Documented.Open(System.String)"/>
            void Open(string reason);
            
            /// <summary>
            /// Determines whether <see cref="IActor.Close()"/> can be invoked from the current state.
            /// </summary>
            /// <returns><c>true</c> when a matching transition exists; otherwise <c>false</c>.</returns>
            bool CanClose();
            
            /// <summary>
            /// Fires <see cref="Trigger.Close"/> from the current state.
            /// </summary>
            void Close();
        }
        
        static partial void Open(string reason)
        {
            _ = reason;
        }
        
        static partial void Close()
        {
        }
        
        static Documented()
        {
            #nullable disable
            Open(default);
            Close();
            #nullable enable
        }
        
        /// <summary>
        /// Factory delegate that creates a new <see cref="IActor"/> at a given <see cref="State"/>, bound to this generated state machine definition.
        /// Useful for dependency injection and unit tests.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <param name="serviceProviderResolver">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>
        /// <param name="state">The starting state. Composite states resolve to their initial leaf.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public delegate IActor CreateActorWithStateFactory(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state);
        
        /// <summary>
        /// Factory delegate that creates a new <see cref="IActor"/> starting at <see cref="GetInitialState()"/>, bound to this generated state machine definition.
        /// Useful for dependency injection and unit tests.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <param name="serviceProviderResolver">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public delegate IActor CreateActorFactory(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver);
        
        private static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
        
        private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> _definition = BuildDefinition();
        
        private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> BuildDefinition()
        {
            var map = new global::Nalu.SharpState.InternalEnumMap<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>>();
            {
                var c = (GeneratedStateConfigurator)Closed;
                map[State.Closed] = c;
            }
            {
                var c = (GeneratedStateConfigurator)Opened;
                map[State.Opened] = c;
            }
            return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>(map);
        }
        
        /// <summary>
        /// Gets the initial root <see cref="State"/> of this generated state machine.
        /// </summary>
        /// <returns>The initial root <see cref="State"/>.</returns>
        public static State GetInitialState() => State.Closed;
        
        /// <summary>
        /// Renders this generated state machine as a Graphviz DOT graph.
        /// </summary>
        /// <returns>The DOT source representing the machine graph.</returns>
        public static string ToDot() => global::Nalu.SharpState.StateMachineExporter.ToDot(_definition, GetInitialState(), "Documented");
        
        /// <summary>
        /// Renders this generated state machine as a Mermaid state diagram.
        /// </summary>
        /// <returns>The Mermaid state diagram source representing the machine graph.</returns>
        public static string ToMermaid() => global::Nalu.SharpState.StateMachineExporter.ToMermaid(_definition, GetInitialState(), "Documented");
        
        /// <summary>
        /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <param name="serviceProviderResolver">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>
        /// <param name="state">The starting state. Composite states resolve to their initial leaf.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public static IActor CreateActorWithState(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state) => new Actor(_definition, state, context, serviceProviderResolver);
        
        /// <summary>
        /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> used to create an actor starting from <see cref="GetInitialState()"/>.</param>
        /// <param name="serviceProviderResolver">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>
        /// <returns>A new <see cref="IActor"/> instance at the machine's initial state.</returns>
        public static IActor CreateActor(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver) => CreateActorWithState(context, serviceProviderResolver, GetInitialState());
        
        private sealed class Actor : IActor
        {
            private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> _engine;
            
            internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> definition, State currentState, global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver)
            {
                _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>(definition, currentState, context, this, serviceProviderResolver);
            }
            
            public State CurrentState => _engine.CurrentState;
            
            public global::Sample.Ctx Context => _engine.Context;
            
            public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled
            {
                get => _engine.OnUnhandled;
                set => _engine.OnUnhandled = value;
            }
            
            public event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged
            {
                add => _engine.StateChanged += value;
                remove => _engine.StateChanged -= value;
            }
            
            public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed
            {
                add => _engine.ReactionFailed += value;
                remove => _engine.ReactionFailed -= value;
            }
            
            public bool IsIn(State state) => _engine.IsIn(state);
            
            public bool CanOpen(string reason) => _engine.CanFire(Trigger.Open, new TriggerArgs(new OpenArgs(reason)));
            
            public void Open(string reason) => _engine.Fire(Trigger.Open, new TriggerArgs(new OpenArgs(reason)));
            
            public bool CanClose() => _engine.CanFire(Trigger.Close, TriggerArgs.ForClose());
            
            public void Close() => _engine.Fire(Trigger.Close, TriggerArgs.ForClose());
        }
        
        private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>, IStateConfigurator
        {
            internal void ApplyParent(State parent) => SetParent(parent);
            
            internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
            
            public IStateConfigurator OnOpen(Action<global::Nalu.SharpState.IStateTriggerArgsBuilder<global::Sample.Ctx, State, IActor, OpenArgs>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, TriggerArgs, State, IActor, OpenArgs>(static args => args.TryGetValue(out OpenArgs value) ? value : throw new global::System.InvalidOperationException("Trigger argument payload does not match trigger 'Open'."));
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Open, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnClose(Action<global::Nalu.SharpState.IStateTriggerBuilder<global::Sample.Ctx, State, IActor>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, TriggerArgs, State, IActor>();
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Close, builder.BuildTransitions());
                return this;
            }
        }
    }
}
