//HintName: Sample.Flat.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using global::Nalu.SharpState;

namespace Sample
{
    public static partial class Flat
    {
        public enum State
        {
            Idle,
            Connected,
        }
        
        public enum Trigger
        {
            Connect,
            Disconnect,
        }
        
        public readonly struct ConnectArgs
        {
            public readonly string DeviceId;
            
            public ConnectArgs(string deviceId)
            {
                DeviceId = deviceId;
            }
            
            public void Deconstruct(out string deviceId)
            {
                deviceId = DeviceId;
            }
        }
        
        public readonly struct DisconnectArgs
        {
        }
        
        public readonly struct TriggerArgs
        {
            private readonly int _kind;
            private readonly ConnectArgs _value1;
            private readonly DisconnectArgs _value2;
            
            public TriggerArgs(ConnectArgs value)
            {
                _kind = 1;
                _value1 = value;
                _value2 = default;
            }
            
            public TriggerArgs(DisconnectArgs value)
            {
                _kind = 2;
                _value1 = default;
                _value2 = value;
            }
            
            public object? Value => _kind switch
            {
                1 => _value1,
                2 => _value2,
                _ => null,
            };
            
            public bool HasValue => _kind != 0;
            
            public bool TryGetValue(out ConnectArgs value)
            {
                value = _kind == 1 ? _value1 : default;
                return _kind == 1;
            }
            
            public bool TryGetValue(out DisconnectArgs value)
            {
                value = _kind == 2 ? _value2 : default;
                return _kind == 2;
            }
            
            public override string ToString() => _kind switch
            {
                1 => _value1.ToString()!,
                2 => _value2.ToString()!,
                _ => "null",
            };
        }
        
        protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>
        {
        }
        
        protected interface IStateConfigurator : global::Nalu.SharpState.IStateLifecycleFluent<IStateConfigurator, global::Sample.Ctx>, IStateConfiguration
        {
            /// <summary>
            /// Configures what happens when <see cref="IActor.Connect(string)"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder{global::Sample.Ctx, State, IActor, ConnectArgs}"/> used by <see cref="IActor.Connect(string)"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnConnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, ConnectArgs>> configure);
            
            /// <summary>
            /// Configures what happens when <see cref="IActor.Disconnect()"/> is invoked.
            /// </summary>
            /// <param name="configure">Configures the <see cref="global::Nalu.SharpState.ISyncStateTriggerBuilder{global::Sample.Ctx, State, IActor, DisconnectArgs}"/> used by <see cref="IActor.Disconnect()"/>.</param>
            /// <returns>The same configurator for chaining.</returns>
            IStateConfigurator OnDisconnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, DisconnectArgs>> configure);
        }
        
        /// <summary>
        /// <see cref="global::Sample.Flat"/> runtime actor.
        /// </summary>
        public interface IActor
        {
            /// <summary>
            /// Gets the current leaf <see cref="State"/>.
            /// </summary>
            State CurrentState { get; }
            
            /// <summary>
            /// Gets the shared context passed to guards, actions, and reactions.
            /// </summary>
            global::Sample.Ctx Context { get; }
            
            /// <summary>
            /// Gets or sets the callback invoked when a trigger has no matching transition.
            /// </summary>
            global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled { get; set; }
            
            /// <summary>
            /// Raised after a transition commits and changes the current state.
            /// </summary>
            event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged;
            
            /// <summary>
            /// Raised when a background reaction scheduled by <c>ReactAsync(...)</c> fails.
            /// </summary>
            event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed;
            
            /// <summary>
            /// Determines whether the current leaf equals <paramref name="state"/> or is contained by it.
            /// </summary>
            /// <param name="state">The state to test against the current hierarchy.</param>
            /// <returns><c>true</c> when the actor is currently in <paramref name="state"/>; otherwise <c>false</c>.</returns>
            bool IsIn(State state);
            
            /// <summary>
            /// Determines whether <see cref="IActor.Connect(string)"/> can be invoked from the current state.
            /// </summary>
            /// <param name="deviceId">The value to test with the trigger.</param>
            /// <returns><c>true</c> when a matching transition exists; otherwise <c>false</c>.</returns>
            bool CanConnect(string deviceId);
            
            /// <summary>
            /// Fires <see cref="Trigger.Connect"/> from the current state.
            /// </summary>
            /// <param name="deviceId">The value to pass to the trigger.</param>
            void Connect(string deviceId);
            
            /// <summary>
            /// Determines whether <see cref="IActor.Disconnect()"/> can be invoked from the current state.
            /// </summary>
            /// <returns><c>true</c> when a matching transition exists; otherwise <c>false</c>.</returns>
            bool CanDisconnect();
            
            /// <summary>
            /// Fires <see cref="Trigger.Disconnect"/> from the current state.
            /// </summary>
            void Disconnect();
        }
        
        static partial void Connect(string deviceId)
        {
            _ = deviceId;
        }
        
        static partial void Disconnect()
        {
        }
        
        static Flat()
        {
            #nullable disable
            Connect(default);
            Disconnect();
            #nullable enable
        }
        
        /// <summary>
        /// Factory delegate that creates a new <see cref="IActor"/> at a given <see cref="State"/>, bound to this generated state machine definition.
        /// Useful for dependency injection and unit tests.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <param name="serviceProviderResolver">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>
        /// <param name="state">The starting state. Composite states resolve to their initial leaf.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public delegate IActor CreateActorWithStateFactory(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state);
        
        /// <summary>
        /// Factory delegate that creates a new <see cref="IActor"/> starting at <see cref="GetInitialState()"/>, bound to this generated state machine definition.
        /// Useful for dependency injection and unit tests.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <param name="serviceProviderResolver">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public delegate IActor CreateActorFactory(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver);
        
        private static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();
        
        private static readonly global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> _definition = BuildDefinition();
        
        private static global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> BuildDefinition()
        {
            var map = new global::Nalu.SharpState.InternalEnumMap<State, global::Nalu.SharpState.IStateConfiguration<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>>();
            {
                var c = (GeneratedStateConfigurator)Idle;
                map[State.Idle] = c;
            }
            {
                var c = (GeneratedStateConfigurator)Connected;
                map[State.Connected] = c;
            }
            return new global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>(map);
        }
        
        /// <summary>
        /// Gets the initial root <see cref="State"/> of this generated state machine.
        /// </summary>
        /// <returns>The initial root <see cref="State"/>.</returns>
        public static State GetInitialState() => State.Idle;
        
        /// <summary>
        /// Renders this generated state machine as a Graphviz DOT graph.
        /// </summary>
        /// <returns>The DOT source representing the machine graph.</returns>
        public static string ToDot() => global::Nalu.SharpState.StateMachineExporter.ToDot(_definition, GetInitialState(), "Flat");
        
        /// <summary>
        /// Renders this generated state machine as a Mermaid state diagram.
        /// </summary>
        /// <returns>The Mermaid state diagram source representing the machine graph.</returns>
        public static string ToMermaid() => global::Nalu.SharpState.StateMachineExporter.ToMermaid(_definition, GetInitialState(), "Flat");
        
        /// <summary>
        /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> passed to guards, actions, and reactions.</param>
        /// <param name="serviceProviderResolver">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>
        /// <param name="state">The starting state. Composite states resolve to their initial leaf.</param>
        /// <returns>A new <see cref="IActor"/> instance.</returns>
        public static IActor CreateActorWithState(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state) => new Actor(_definition, state, context, serviceProviderResolver);
        
        /// <summary>
        /// Creates a new <see cref="IActor"/> bound to this generated state machine definition.
        /// </summary>
        /// <param name="context">The shared <see cref="global::Sample.Ctx"/> used to create an actor starting from <see cref="GetInitialState()"/>.</param>
        /// <param name="serviceProviderResolver">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>
        /// <returns>A new <see cref="IActor"/> instance at the machine's initial state.</returns>
        public static IActor CreateActor(global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver) => CreateActorWithState(context, serviceProviderResolver, GetInitialState());
        
        private sealed class Actor : IActor
        {
            private readonly global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> _engine;
            
            internal Actor(global::Nalu.SharpState.StateMachineDefinition<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor> definition, State currentState, global::Sample.Ctx context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver)
            {
                _engine = new global::Nalu.SharpState.StateMachineEngine<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>(definition, currentState, context, this, serviceProviderResolver);
            }
            
            public State CurrentState => _engine.CurrentState;
            
            public global::Sample.Ctx Context => _engine.Context;
            
            public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled
            {
                get => _engine.OnUnhandled;
                set => _engine.OnUnhandled = value;
            }
            
            public event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged
            {
                add => _engine.StateChanged += value;
                remove => _engine.StateChanged -= value;
            }
            
            public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed
            {
                add => _engine.ReactionFailed += value;
                remove => _engine.ReactionFailed -= value;
            }
            
            public bool IsIn(State state) => _engine.IsIn(state);
            
            public bool CanConnect(string deviceId) => _engine.CanFire(Trigger.Connect, new TriggerArgs(new ConnectArgs(deviceId)));
            
            public void Connect(string deviceId) => _engine.Fire(Trigger.Connect, new TriggerArgs(new ConnectArgs(deviceId)));
            
            public bool CanDisconnect() => _engine.CanFire(Trigger.Disconnect, new TriggerArgs(new DisconnectArgs()));
            
            public void Disconnect() => _engine.Fire(Trigger.Disconnect, new TriggerArgs(new DisconnectArgs()));
        }
        
        private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<global::Sample.Ctx, TriggerArgs, State, Trigger, IActor>, IStateConfigurator
        {
            internal void ApplyParent(State parent) => SetParent(parent);
            
            internal void ApplyInitialChild(State initial) => SetInitialChild(initial);
            
            public IStateConfigurator OnConnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, ConnectArgs>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, TriggerArgs, State, IActor, ConnectArgs>(static args => args.TryGetValue(out ConnectArgs value) ? value : throw new global::System.InvalidOperationException("Trigger argument payload does not match trigger 'Connect'."));
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Connect, builder.BuildTransitions());
                return this;
            }
            
            public IStateConfigurator OnDisconnect(Action<global::Nalu.SharpState.ISyncStateTriggerBuilder<global::Sample.Ctx, State, IActor, DisconnectArgs>> configure)
            {
                var builder = new global::Nalu.SharpState.StateTriggerBuilder<global::Sample.Ctx, TriggerArgs, State, IActor, DisconnectArgs>(static args => args.TryGetValue(out DisconnectArgs value) ? value : throw new global::System.InvalidOperationException("Trigger argument payload does not match trigger 'Disconnect'."));
                configure(builder);
                builder.Validate();
                AddTransitions(Trigger.Disconnect, builder.BuildTransitions());
                return this;
            }
        }
    }
}
