using Microsoft.CodeAnalysis;
using Nalu.SharpState.Generators.Model;

namespace Nalu.SharpState.Generators.Emit;

/// <summary>
/// Turns a <see cref="StateMachineModel"/> into the generated <c>.g.cs</c> source text and reports any
/// diagnostics accumulated during model extraction.
/// </summary>
internal static class StateMachineEmitter
{
    public static void Emit(SourceProductionContext context, StateMachineModel model)
    {
        foreach (var diagnostic in model.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (model.Diagnostics.Any(d => d.Descriptor.DefaultSeverity == DiagnosticSeverity.Error))
        {
            return;
        }

        var writer = new SourceWriter();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("#pragma warning disable CS1591");
        writer.WriteBlankLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using global::Nalu.SharpState;");
        writer.WriteBlankLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            writer.WriteLine($"namespace {model.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        foreach (var containing in model.ContainingTypes)
        {
            writer.WriteLine($"{containing.Accessibility} partial {containing.Keyword} {containing.Name}{containing.TypeParameters}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        EmitMachineBody(writer, model);

        for (var i = 0; i < model.ContainingTypes.Count; i++)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        if (hasNamespace)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        context.AddSource(SanitizeHintName(model.Hintname), writer.ToString());
    }

    private static string SanitizeHintName(string hint) => hint.Replace('/', '.').Replace('\\', '.');

    private static void EmitMachineBody(SourceWriter w, StateMachineModel m)
    {
        var context = m.ContextTypeDisplay;
        var className = m.ClassName;
        var typeParams = m.TypeParameters;

        var staticModifier = m.IsStaticClass ? "static " : string.Empty;
        w.WriteLine($"{m.ClassAccessibility} {staticModifier}partial {m.ClassKeyword} {className}{typeParams}");
        using (w.Block())
        {
            EmitStateEnum(w, m);
            w.WriteBlankLine();
            EmitTriggerEnum(w, m);
            w.WriteBlankLine();
            EmitTriggerArgsTypes(w, m);
            w.WriteBlankLine();
            EmitConfigurationInterface(w, context);
            w.WriteBlankLine();
            EmitConfiguratorInterface(w, context, m);
            w.WriteBlankLine();
            EmitActorInterface(w, context, m);
            w.WriteBlankLine();
            if (m.Triggers.Count > 0)
            {
                EmitTriggerPartialImplementations(w, m);
                w.WriteBlankLine();
                EmitTriggerDefinitionReferenceConstructor(w, m);
                w.WriteBlankLine();
            }

            EmitCreateActorFactoryDelegates(w, context);
            w.WriteBlankLine();
            w.WriteLine("private static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();");
            w.WriteBlankLine();
            w.WriteLine($"private static readonly global::Nalu.SharpState.StateMachineDefinition<{context}, TriggerArgs, State, Trigger, IActor> _definition = BuildDefinition();");
            w.WriteBlankLine();
            EmitBuildDefinition(w, context, m);
            w.WriteBlankLine();
            EmitGetInitialStateDocs(w);
            w.WriteLine($"public static State GetInitialState() => State.{m.RootInitialState};");
            w.WriteBlankLine();
            EmitToDotDocs(w);
            w.WriteLine($"public static string ToDot() => global::Nalu.SharpState.StateMachineExporter.ToDot(_definition, GetInitialState(), \"{m.ClassName}\");");
            w.WriteBlankLine();
            EmitToMermaidDocs(w);
            w.WriteLine($"public static string ToMermaid() => global::Nalu.SharpState.StateMachineExporter.ToMermaid(_definition, GetInitialState(), \"{m.ClassName}\");");
            w.WriteBlankLine();
            EmitCreateActorWithStateMethodDocs(w, context);
            w.WriteLine($"public static IActor CreateActorWithState({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state) => new Actor(_definition, state, context, serviceProviderResolver);");
            w.WriteBlankLine();
            EmitCreateActorMethodDocs(w, context);
            w.WriteLine($"public static IActor CreateActor({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver) => CreateActorWithState(context, serviceProviderResolver, GetInitialState());");
            w.WriteBlankLine();
            EmitActorClass(w, context, m);
            w.WriteBlankLine();
            EmitGeneratedConfigurator(w, context, m);
            EmitRegionRegistrars(w, context, m);
        }
    }

    private static void EmitTriggerPartialImplementations(SourceWriter w, StateMachineModel m)
    {
        for (var i = 0; i < m.Triggers.Count; i++)
        {
            var t = m.Triggers[i];
            var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
            var staticModifier = t.IsStatic ? "static " : string.Empty;
            // Match declaring partial: default (private) accessibility is usually written without the "private" keyword (CS8799).
            var accessPrefix = t.AccessibilityKeyword == "private"
                ? string.Empty
                : $"{t.AccessibilityKeyword} ";
            w.WriteLine($"{accessPrefix}{staticModifier}partial void {t.Name}({paramList})");
            using (w.Block())
            {
                foreach (var p in t.Parameters)
                {
                    w.WriteLine($"_ = {p.Name};");
                }
            }

            if (i + 1 < m.Triggers.Count)
            {
                w.WriteBlankLine();
            }
        }
    }

    /// <summary>
    /// Emits a type constructor that calls each trigger with <c>default</c> so tooling sees the overloads referenced,
    /// and (for non-static machines) hides the implicit public constructor.
    /// </summary>
    private static void EmitTriggerDefinitionReferenceConstructor(SourceWriter w, StateMachineModel m)
    {
        var machineName = m.ClassName;

        // Static classes cannot have instance constructors; everything else uses a private ctor so the machine type
        // is not instantiable from user code while still referencing trigger parameters from generated code.
        if (m.IsStaticClass)
        {
            w.WriteLine($"static {machineName}()");
        }
        else
        {
            w.WriteLine($"private {machineName}()");
        }

        using (w.Block())
        {
            w.WriteLine("#nullable disable");
            foreach (var t in m.Triggers)
            {
                w.Write(t.Name);
                w.Write("(");
                for (var i = 0; i < t.Parameters.Count; i++)
                {
                    if (i > 0)
                    {
                        w.Write(", ");
                    }

                    w.Write("default");
                }

                w.WriteLine(");");
            }

            w.WriteLine("#nullable enable");
        }
    }

    private static RegionNode BuildRegionTree(StateMachineModel m)
    {
        var root = new RegionNode(string.Empty);
        foreach (var s in m.States)
        {
            var node = root;
            if (!string.IsNullOrEmpty(s.RegionPath))
            {
                foreach (var seg in s.RegionPath.Split('.'))
                {
                    if (!node.Children.TryGetValue(seg, out var next))
                    {
                        next = new RegionNode(seg);
                        node.Children[seg] = next;
                    }
                    node = next;
                }
            }

            node.States.Add(s);
        }

        return root;
    }

    private static void EmitRegionRegistrars(SourceWriter w, string context, StateMachineModel m)
    {
        var root = BuildRegionTree(m);
        foreach (var top in root.Children.Values)
        {
            w.WriteBlankLine();
            EmitRegionClass(w, context, top);
        }
    }

    private static void EmitRegionClass(SourceWriter w, string context, RegionNode node)
    {
        w.WriteLine($"partial class {node.Name}");
        using (w.Block())
        {
            w.WriteLine(
                $"internal static void __Register(global::Nalu.SharpState.InternalEnumMap<State, global::Nalu.SharpState.IStateConfiguration<{context}, TriggerArgs, State, Trigger, IActor>> map)");
            using (w.Block())
            {
                foreach (var s in node.States)
                {
                    EmitStateRegistration(w, s);
                }

                foreach (var child in node.Children.Values)
                {
                    w.WriteLine($"{child.Name}.__Register(map);");
                }
            }

            foreach (var child in node.Children.Values)
            {
                w.WriteBlankLine();
                EmitRegionClass(w, context, child);
            }
        }
    }

    private static void EmitStateRegistration(SourceWriter w, StateModel s)
    {
        using (w.Block())
        {
            w.WriteLine($"var c = (GeneratedStateConfigurator){s.Name};");
            if (s.ParentState is not null)
            {
                w.WriteLine($"c.ApplyParent(State.{s.ParentState});");
            }
            if (s.InitialChildState is not null)
            {
                w.WriteLine($"c.ApplyInitialChild(State.{s.InitialChildState});");
            }
            w.WriteLine($"map[State.{s.Name}] = c;");
        }
    }

    private sealed class RegionNode
    {
        public RegionNode(string name)
        {
            Name = name;
        }

        public string Name { get; }
        public SortedDictionary<string, RegionNode> Children { get; } = new(StringComparer.Ordinal);
        public List<StateModel> States { get; } = new();
    }

    private static void EmitStateEnum(SourceWriter w, StateMachineModel m)
    {
        w.WriteLine("public enum State");
        using (w.Block())
        {
            foreach (var s in m.States)
            {
                EmitInheritdoc(w, s.DocumentationCommentId);
                w.WriteLine($"{s.Name},");
            }
        }
    }

    private static void EmitTriggerEnum(SourceWriter w, StateMachineModel m)
    {
        w.WriteLine("public enum Trigger");
        using (w.Block())
        {
            foreach (var t in m.Triggers)
            {
                EmitInheritdoc(w, t.DocumentationCommentId);
                w.WriteLine($"{t.Name},");
            }
        }
    }

    private static void EmitTriggerArgsTypes(SourceWriter w, StateMachineModel m)
    {
        foreach (var trigger in m.Triggers)
        {
            if (trigger.Parameters.Count > 0)
            {
                EmitTriggerArgsPayload(w, trigger);
                w.WriteBlankLine();
            }
        }

        w.WriteLine("public readonly struct TriggerArgs");
        using (w.Block())
        {
            w.WriteLine("private readonly int _kind;");

            for (var i = 0; i < m.Triggers.Count; i++)
            {
                var trigger = m.Triggers[i];
                if (trigger.Parameters.Count > 0)
                {
                    w.WriteLine($"private readonly {ArgsTypeName(trigger)} _value{i + 1};");
                }
            }

            if (m.Triggers.Count > 0)
            {
                w.WriteBlankLine();
            }

            w.WriteLine("private TriggerArgs(int kind)");
            using (w.Block())
            {
                w.WriteLine("_kind = kind;");
            }

            for (var i = 0; i < m.Triggers.Count; i++)
            {
                var trigger = m.Triggers[i];
                if (trigger.Parameters.Count == 0)
                {
                    continue;
                }

                var argType = ArgsTypeName(trigger);
                w.WriteBlankLine();
                w.WriteLine($"public TriggerArgs({argType} value)");
                using (w.Block())
                {
                    w.WriteLine($"_kind = {i + 1};");
                    for (var j = 0; j < m.Triggers.Count; j++)
                    {
                        var tj = m.Triggers[j];
                        if (tj.Parameters.Count == 0)
                        {
                            continue;
                        }

                        w.WriteLine($"_value{j + 1} = {(i == j ? "value" : "default")};");
                    }
                }
            }

            for (var i = 0; i < m.Triggers.Count; i++)
            {
                var trigger = m.Triggers[i];
                if (trigger.Parameters.Count > 0)
                {
                    continue;
                }

                w.WriteBlankLine();
                w.WriteLine($"public static TriggerArgs For{trigger.Name}() => new TriggerArgs({i + 1});");
            }

            if (m.Triggers.Count > 0)
            {
                w.WriteBlankLine();
            }

            if (m.Triggers.Count == 0)
            {
                w.WriteLine("public object? Value => null;");
            }
            else
            {
                w.WriteLine("public object? Value => _kind switch");
                w.WriteLine("{");
                w.Indent++;
                for (var i = 0; i < m.Triggers.Count; i++)
                {
                    var trigger = m.Triggers[i];
                    var arm = trigger.Parameters.Count > 0 ? $"_value{i + 1}" : "null";
                    w.WriteLine($"{i + 1} => {arm},");
                }

                w.WriteLine("_ => null,");
                w.Indent--;
                w.WriteLine("};");
            }

            w.WriteBlankLine();
            w.WriteLine("public bool HasValue => _kind != 0;");

            for (var i = 0; i < m.Triggers.Count; i++)
            {
                var trigger = m.Triggers[i];
                if (trigger.Parameters.Count == 0)
                {
                    continue;
                }

                var argType = ArgsTypeName(trigger);
                w.WriteBlankLine();
                w.WriteLine($"public bool TryGetValue(out {argType} value)");
                using (w.Block())
                {
                    w.WriteLine($"value = _kind == {i + 1} ? _value{i + 1} : default;");
                    w.WriteLine($"return _kind == {i + 1};");
                }
            }

            w.WriteBlankLine();
            EmitTriggerArgsUnionToString(w, m);
        }
    }

    private static void EmitTriggerArgsUnionToString(SourceWriter w, StateMachineModel m)
    {
        if (m.Triggers.Count == 0)
        {
            w.WriteLine("public override string? ToString() => null;");
            return;
        }

        w.WriteLine("public override string? ToString() => _kind switch");
        w.WriteLine("{");
        w.Indent++;
        for (var i = 0; i < m.Triggers.Count; i++)
        {
            var trigger = m.Triggers[i];
            if (trigger.Parameters.Count > 0)
            {
                w.WriteLine($"{i + 1} => _value{i + 1}.ToString(),");
            }
            else
            {
                w.WriteLine($"{i + 1} => null,");
            }
        }

        w.WriteLine("_ => null,");
        w.Indent--;
        w.WriteLine("};");
    }

    private static void EmitTriggerArgsPayload(SourceWriter w, TriggerModel trigger)
    {
        w.WriteLine($"public readonly struct {ArgsTypeName(trigger)}");
        using (w.Block())
        {
            foreach (var parameter in trigger.Parameters)
            {
                w.WriteLine($"public readonly {parameter.TypeDisplay} {FieldName(parameter.Name)};");
            }

            w.WriteBlankLine();
            var parameterList = string.Join(", ", trigger.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
            w.WriteLine($"public {ArgsTypeName(trigger)}({parameterList})");
            using (w.Block())
            {
                foreach (var parameter in trigger.Parameters)
                {
                    w.WriteLine($"{FieldName(parameter.Name)} = {parameter.Name};");
                }
            }

            w.WriteBlankLine();
            var deconstructParams = string.Join(", ", trigger.Parameters.Select(p => $"out {p.TypeDisplay} {p.Name}"));
            w.WriteLine($"public void Deconstruct({deconstructParams})");
            using (w.Block())
            {
                foreach (var parameter in trigger.Parameters)
                {
                    w.WriteLine($"{parameter.Name} = {FieldName(parameter.Name)};");
                }
            }
        }
    }

    private static void EmitConfigurationInterface(SourceWriter w, string context)
    {
        w.WriteLine($"protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<{context}, TriggerArgs, State, Trigger, IActor>");
        using (w.Block())
        { }
    }

    private static void EmitConfiguratorInterface(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine($"protected interface IStateConfigurator : global::Nalu.SharpState.IStateLifecycleFluent<IStateConfigurator, {context}>, IStateConfiguration");
        using (w.Block())
        {
            for (var i = 0; i < m.Triggers.Count; i++)
            {
                var t = m.Triggers[i];
                EmitConfiguratorTriggerDocs(w, context, t);
                w.WriteLine($"IStateConfigurator On{t.Name}(Action<{BuilderInterfaceType(context, t)}> configure);");
                if (i < m.Triggers.Count - 1)
                {
                    w.WriteBlankLine();
                }
            }
        }
    }

    private static void EmitActorInterface(SourceWriter w, string context, StateMachineModel m)
    {
        var machineTypeCref = ToDocCref(MachineTypeCref(m));
        w.WriteLine("/// <summary>");
        w.WriteLine($"/// <see cref=\"{machineTypeCref}\"/> runtime actor.");
        w.WriteLine("/// </summary>");
        w.WriteLine("public interface IActor");
        using (w.Block())
        {
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Gets the current leaf <see cref=\"State\"/>.");
            w.WriteLine("/// </summary>");
            w.WriteLine("State CurrentState { get; }");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Gets the shared context passed to guards, actions, and reactions.");
            w.WriteLine("/// </summary>");
            w.WriteLine($"{context} Context {{ get; }}");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Gets or sets the callback invoked when a trigger has no matching transition.");
            w.WriteLine("/// </summary>");
            w.WriteLine("global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled { get; set; }");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Raised after a transition commits and changes the current state.");
            w.WriteLine("/// </summary>");
            w.WriteLine("event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged;");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Raised when post-transition asynchronous work fails after the transition has committed.");
            w.WriteLine("/// </summary>");
            w.WriteLine("event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed;");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Determines whether the current leaf equals <paramref name=\"state\"/> or is contained by it.");
            w.WriteLine("/// </summary>");
            w.WriteLine("/// <param name=\"state\">The state to test against the current hierarchy.</param>");
            w.WriteLine("/// <returns><c>true</c> when the actor is currently in <paramref name=\"state\"/>; otherwise <c>false</c>.</returns>");
            w.WriteLine("bool IsIn(State state);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitActorInterfaceCanTriggerMethod(w, t);
                w.WriteBlankLine();
                EmitActorInterfaceTriggerMethod(w, t);
                w.WriteBlankLine();
                EmitActorInterfaceAsyncTriggerMethod(w, t);
            }
        }
    }

    private static void EmitCreateActorFactoryDelegates(SourceWriter w, string context)
    {
        EmitCreateActorWithStateFactoryDelegate(w, context);
        w.WriteBlankLine();
        EmitCreateActorFactoryDelegate(w, context);
    }

    private static void EmitCreateActorWithStateFactoryDelegate(SourceWriter w, string context)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Factory delegate that creates a new <see cref=\"IActor\"/> at a given <see cref=\"State\"/>, bound to this generated state machine definition.");
        w.WriteLine("/// Useful for dependency injection and unit tests.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> passed to guards, actions, and reactions.</param>");
        w.WriteLine("/// <param name=\"serviceProviderResolver\">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>");
        w.WriteLine("/// <param name=\"state\">The starting state. Composite states resolve to their initial leaf.</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance.</returns>");
        w.WriteLine($"public delegate IActor CreateActorWithStateFactory({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver, State state);");
    }

    private static void EmitCreateActorFactoryDelegate(SourceWriter w, string context)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Factory delegate that creates a new <see cref=\"IActor\"/> starting at <see cref=\"GetInitialState()\"/>, bound to this generated state machine definition.");
        w.WriteLine("/// Useful for dependency injection and unit tests.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> passed to guards, actions, and reactions.</param>");
        w.WriteLine("/// <param name=\"serviceProviderResolver\">Resolver used during transitions and scoped providers for <c>ReactAsync</c>.</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance.</returns>");
        w.WriteLine($"public delegate IActor CreateActorFactory({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver);");
    }

    private static void EmitBuildDefinition(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine($"private static global::Nalu.SharpState.StateMachineDefinition<{context}, TriggerArgs, State, Trigger, IActor> BuildDefinition()");
        using (w.Block())
        {
            w.WriteLine($"var map = new global::Nalu.SharpState.InternalEnumMap<State, global::Nalu.SharpState.IStateConfiguration<{context}, TriggerArgs, State, Trigger, IActor>>();");

            var root = BuildRegionTree(m);
            foreach (var s in root.States)
            {
                EmitStateRegistration(w, s);
            }

            foreach (var child in root.Children.Values)
            {
                w.WriteLine($"{child.Name}.__Register(map);");
            }

            w.WriteLine($"return new global::Nalu.SharpState.StateMachineDefinition<{context}, TriggerArgs, State, Trigger, IActor>(map);");
        }
    }

    private static void EmitActorClass(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine("private sealed class Actor : IActor");
        using (w.Block())
        {
            w.WriteLine($"private readonly global::Nalu.SharpState.StateMachineEngine<{context}, TriggerArgs, State, Trigger, IActor> _engine;");
            w.WriteBlankLine();
            w.WriteLine(
                $"internal Actor(global::Nalu.SharpState.StateMachineDefinition<{context}, TriggerArgs, State, Trigger, IActor> definition, State currentState, {context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver serviceProviderResolver)");
            using (w.Block())
            {
                w.WriteLine(
                    $"_engine = new global::Nalu.SharpState.StateMachineEngine<{context}, TriggerArgs, State, Trigger, IActor>(definition, currentState, context, this, serviceProviderResolver);");
            }

            w.WriteBlankLine();
            w.WriteLine("public State CurrentState => _engine.CurrentState;");
            w.WriteBlankLine();
            w.WriteLine($"public {context} Context => _engine.Context;");
            w.WriteBlankLine();
            w.WriteLine("public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger, TriggerArgs>? OnUnhandled");
            using (w.Block())
            {
                w.WriteLine("get => _engine.OnUnhandled;");
                w.WriteLine("set => _engine.OnUnhandled = value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public event global::Nalu.SharpState.StateChangedHandler<State, Trigger, TriggerArgs>? StateChanged");
            using (w.Block())
            {
                w.WriteLine("add => _engine.StateChanged += value;");
                w.WriteLine("remove => _engine.StateChanged -= value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger, TriggerArgs>? ReactionFailed");
            using (w.Block())
            {
                w.WriteLine("add => _engine.ReactionFailed += value;");
                w.WriteLine("remove => _engine.ReactionFailed -= value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public bool IsIn(State state) => _engine.IsIn(state);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitActorCanTriggerMethod(w, t);
                w.WriteBlankLine();
                EmitActorTriggerMethod(w, t);
                w.WriteBlankLine();
                EmitActorAsyncTriggerMethod(w, t);
            }
        }
    }

    private static void EmitActorCanTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var triggerArgs = TriggerArgsFactory(t);
        w.WriteLine($"public bool Can{t.Name}({paramList}) => _engine.CanFire(Trigger.{t.Name}, {triggerArgs});");
    }

    private static void EmitActorTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var triggerArgs = TriggerArgsFactory(t);
        w.WriteLine($"public void {t.Name}({paramList}) => _engine.Fire(Trigger.{t.Name}, {triggerArgs});");
    }

    private static void EmitActorAsyncTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var triggerArgs = TriggerArgsFactory(t);
        w.WriteLine($"public global::System.Threading.Tasks.ValueTask {t.Name}Async({paramList}) => _engine.FireAsync(Trigger.{t.Name}, {triggerArgs});");
    }

    private static void EmitGeneratedConfigurator(SourceWriter w, string context, StateMachineModel m)
    {
        w.WriteLine(
            $"private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<{context}, TriggerArgs, State, Trigger, IActor>, IStateConfigurator");
        using (w.Block())
        {
            w.WriteLine("internal void ApplyParent(State parent) => SetParent(parent);");
            w.WriteBlankLine();
            w.WriteLine("internal void ApplyInitialChild(State initial) => SetInitialChild(initial);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitConfiguratorTriggerMethod(w, context, t);
            }
        }
    }

    private static void EmitConfiguratorTriggerMethod(SourceWriter w, string context, TriggerModel t)
    {
        var builderType = BuilderInterfaceType(context, t);
        var concreteBuilder = ConcreteBuilderType(context, t);
        w.WriteLine($"public IStateConfigurator On{t.Name}(Action<{builderType}> configure)");
        using (w.Block())
        {
            if (t.Parameters.Count == 0)
            {
                w.WriteLine($"var builder = new {concreteBuilder}();");
            }
            else
            {
                w.WriteLine($"var builder = new {concreteBuilder}(static args => args.TryGetValue(out {ArgsTypeName(t)} value) ? value : throw new global::System.InvalidOperationException(\"Trigger argument payload does not match trigger '{t.Name}'.\"));");
            }

            w.WriteLine("configure(builder);");
            w.WriteLine("builder.Validate();");
            w.WriteLine($"AddTransitions(Trigger.{t.Name}, builder.BuildTransitions());");
            w.WriteLine("return this;");
        }
    }

    private static void EmitActorInterfaceTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        if (!string.IsNullOrWhiteSpace(t.DocumentationCommentId))
        {
            EmitInheritdoc(w, t.DocumentationCommentId);
        }
        else
        {
            w.WriteLine("/// <summary>");
            w.WriteLine($"/// Fires <see cref=\"Trigger.{t.Name}\"/> from the current state.");
            w.WriteLine("/// </summary>");
            foreach (var parameter in t.Parameters)
            {
                w.WriteLine($"/// <param name=\"{parameter.Name}\">The value to pass to the trigger.</param>");
            }
        }

        w.WriteLine($"void {t.Name}({paramList});");
    }

    private static void EmitActorInterfaceAsyncTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        w.WriteLine("/// <summary>");
        w.WriteLine($"/// Fires <see cref=\"Trigger.{t.Name}\"/> from the current state and awaits post-transition asynchronous work.");
        w.WriteLine("/// </summary>");
        foreach (var parameter in t.Parameters)
        {
            w.WriteLine($"/// <param name=\"{parameter.Name}\">The value to pass to the trigger.</param>");
        }

        w.WriteLine($"global::System.Threading.Tasks.ValueTask {t.Name}Async({paramList});");
    }

    private static void EmitActorInterfaceCanTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var actorMethodCref = ActorMethodCref(t);
        w.WriteLine("/// <summary>");
        w.WriteLine($"/// Determines whether <see cref=\"{actorMethodCref}\"/> can be invoked from the current state.");
        w.WriteLine("/// </summary>");
        foreach (var parameter in t.Parameters)
        {
            w.WriteLine($"/// <param name=\"{parameter.Name}\">The value to test with the trigger.</param>");
        }
        w.WriteLine("/// <returns><c>true</c> when a matching transition exists; otherwise <c>false</c>.</returns>");
        w.WriteLine($"bool Can{t.Name}({paramList});");
    }

    private static void EmitGetInitialStateDocs(SourceWriter w)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Gets the initial root <see cref=\"State\"/> of this generated state machine.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <returns>The initial root <see cref=\"State\"/>.</returns>");
    }

    private static void EmitCreateActorWithStateMethodDocs(SourceWriter w, string context)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Creates a new <see cref=\"IActor\"/> bound to this generated state machine definition.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> passed to guards, actions, and reactions.</param>");
        w.WriteLine("/// <param name=\"serviceProviderResolver\">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>");
        w.WriteLine("/// <param name=\"state\">The starting state. Composite states resolve to their initial leaf.</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance.</returns>");
    }

    private static void EmitCreateActorMethodDocs(SourceWriter w, string context)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Creates a new <see cref=\"IActor\"/> bound to this generated state machine definition.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> used to create an actor starting from <see cref=\"GetInitialState()\"/>.</param>");
        w.WriteLine("/// <param name=\"serviceProviderResolver\">Resolver for transition services and scoped <c>ReactAsync</c> providers.</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance at the machine's initial state.</returns>");
    }

    private static void EmitToDotDocs(SourceWriter w)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Renders this generated state machine as a Graphviz DOT graph.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <returns>The DOT source representing the machine graph.</returns>");
    }

    private static void EmitToMermaidDocs(SourceWriter w)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Renders this generated state machine as a Mermaid state diagram.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <returns>The Mermaid state diagram source representing the machine graph.</returns>");
    }

    private static void EmitConfiguratorTriggerDocs(SourceWriter w, string context, TriggerModel t)
    {
        var actorMethodCref = ActorMethodCref(t);
        var builderCref = ToDocCref(BuilderInterfaceType(context, t));
        w.WriteLine("/// <summary>");
        w.WriteLine($"/// Configures what happens when <see cref=\"{actorMethodCref}\"/> is invoked.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"configure\">Configures the <see cref=\"{builderCref}\"/> used by <see cref=\"{actorMethodCref}\"/>.</param>");
        w.WriteLine("/// <returns>The same configurator for chaining.</returns>");
    }

    private static string BuilderInterfaceType(string context, TriggerModel t)
        => t.Parameters.Count == 0
            ? $"global::Nalu.SharpState.IStateTriggerBuilder<{context}, State, IActor>"
            : $"global::Nalu.SharpState.IStateTriggerArgsBuilder<{context}, State, IActor, {ArgsTypeName(t)}>";

    private static string ConcreteBuilderType(string context, TriggerModel t)
        => t.Parameters.Count == 0
            ? $"global::Nalu.SharpState.StateTriggerBuilder<{context}, TriggerArgs, State, IActor>"
            : $"global::Nalu.SharpState.StateTriggerBuilder<{context}, TriggerArgs, State, IActor, {ArgsTypeName(t)}>";

    private static string TriggerArgsFactory(TriggerModel t)
        => t.Parameters.Count == 0
            ? $"TriggerArgs.For{t.Name}()"
            : $"new TriggerArgs(new {ArgsTypeName(t)}({string.Join(", ", t.Parameters.Select(p => p.Name))}))";

    private static string ArgsTypeName(TriggerModel t) => $"{t.Name}Args";

    private static string FieldName(string parameterName)
        => string.IsNullOrEmpty(parameterName)
            ? parameterName
            : char.ToUpperInvariant(parameterName[0]) + parameterName.Substring(1);

    private static string ActorMethodCref(TriggerModel t)
    {
        if (t.Parameters.Count == 0)
        {
            return $"IActor.{t.Name}()";
        }

        var parameterTypes = string.Join(", ", t.Parameters.Select(p => p.TypeDisplay));
        return ToDocCref($"IActor.{t.Name}({parameterTypes})");
    }

    // XML documentation cref attributes use { } for type arguments, not C# < >.
    private static string ToDocCref(string csharpTypeOrMemberId) =>
        csharpTypeOrMemberId.Replace('<', '{').Replace('>', '}');

    private static string MachineTypeCref(StateMachineModel m)
    {
        var typePath = string.Join(".", m.ContainingTypes.Select(t => t.Name).Append(m.ClassName));
        return string.IsNullOrEmpty(m.Namespace)
            ? typePath
            : $"global::{m.Namespace}.{typePath}";
    }

    private static void EmitInheritdoc(SourceWriter w, string? documentationCommentId)
    {
        if (string.IsNullOrWhiteSpace(documentationCommentId))
        {
            return;
        }

        w.WriteLine($"/// <inheritdoc cref=\"{documentationCommentId}\"/>");
    }
}
