using Microsoft.CodeAnalysis;
using Nalu.SharpState.Generators.Model;

namespace Nalu.SharpState.Generators.Emit;

/// <summary>
/// Turns a <see cref="StateMachineModel"/> into the generated <c>.g.cs</c> source text and reports any
/// diagnostics accumulated during model extraction.
/// </summary>
internal static class StateMachineEmitter
{
    public static void Emit(SourceProductionContext context, StateMachineModel model)
    {
        foreach (var diagnostic in model.Diagnostics)
        {
            context.ReportDiagnostic(diagnostic.ToDiagnostic());
        }

        if (model.Diagnostics.Any(d => d.Descriptor.DefaultSeverity == DiagnosticSeverity.Error))
        {
            return;
        }

        var writer = new SourceWriter();
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("#pragma warning disable CS1591");
        writer.WriteBlankLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Threading.Tasks;");
        writer.WriteLine("using global::Nalu.SharpState;");
        writer.WriteBlankLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            writer.WriteLine($"namespace {model.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        foreach (var containing in model.ContainingTypes)
        {
            writer.WriteLine($"{containing.Accessibility} partial {containing.Keyword} {containing.Name}{containing.TypeParameters}");
            writer.WriteLine("{");
            writer.Indent++;
        }

        EmitMachineBody(writer, model);

        for (var i = 0; i < model.ContainingTypes.Count; i++)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        if (hasNamespace)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        context.AddSource(SanitizeHintName(model.Hintname), writer.ToString());
    }

    private static string SanitizeHintName(string hint) => hint.Replace('/', '.').Replace('\\', '.');

    private static void EmitMachineBody(SourceWriter w, StateMachineModel m)
    {
        var context = m.ContextTypeDisplay;
        var serviceProvider = m.ServiceProviderTypeDisplay;
        var className = m.ClassName;
        var typeParams = m.TypeParameters;

        var staticModifier = m.IsStaticClass ? "static " : string.Empty;
        w.WriteLine($"{m.ClassAccessibility} {staticModifier}partial {m.ClassKeyword} {className}{typeParams}");
        using (w.Block())
        {
            EmitStateEnum(w, m);
            w.WriteBlankLine();
            EmitTriggerEnum(w, m);
            w.WriteBlankLine();
            EmitConfigurationInterface(w, context, serviceProvider);
            w.WriteBlankLine();
            EmitConfiguratorInterface(w, context, serviceProvider, m);
            w.WriteBlankLine();
            EmitActorInterface(w, context, serviceProvider, m);
            w.WriteBlankLine();
            if (m.Triggers.Count > 0)
            {
                EmitTriggerDefinitionReferenceConstructor(w, m);
                w.WriteBlankLine();
            }

            EmitCreateActorFactoryDelegates(w, context, serviceProvider);
            w.WriteBlankLine();
            w.WriteLine("private static IStateConfigurator ConfigureState() => new GeneratedStateConfigurator();");
            w.WriteBlankLine();
            w.WriteLine($"private static readonly global::Nalu.SharpState.StateMachineDefinition<{context}, {serviceProvider}, State, Trigger, IActor> _definition = BuildDefinition();");
            w.WriteBlankLine();
            EmitBuildDefinition(w, context, serviceProvider, m);
            w.WriteBlankLine();
            EmitGetInitialStateDocs(w);
            w.WriteLine($"public static State GetInitialState() => State.{m.RootInitialState};");
            w.WriteBlankLine();
            EmitToDotDocs(w);
            w.WriteLine($"public static string ToDot() => global::Nalu.SharpState.StateMachineExporter.ToDot(_definition, GetInitialState(), \"{m.ClassName}\");");
            w.WriteBlankLine();
            EmitToMermaidDocs(w);
            w.WriteLine($"public static string ToMermaid() => global::Nalu.SharpState.StateMachineExporter.ToMermaid(_definition, GetInitialState(), \"{m.ClassName}\");");
            w.WriteBlankLine();
            EmitCreateActorWithStateMethodDocs(w, context, serviceProvider);
            w.WriteLine($"public static IActor CreateActorWithState({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver<{serviceProvider}> serviceProviderResolver, State state) => new Actor(_definition, state, context, serviceProviderResolver);");
            w.WriteBlankLine();
            EmitCreateActorMethodDocs(w, context, serviceProvider);
            w.WriteLine($"public static IActor CreateActor({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver<{serviceProvider}> serviceProviderResolver) => CreateActorWithState(context, serviceProviderResolver, GetInitialState());");
            w.WriteBlankLine();
            EmitActorClass(w, context, serviceProvider, m);
            w.WriteBlankLine();
            EmitGeneratedConfigurator(w, context, serviceProvider, m);
            EmitRegionRegistrars(w, context, serviceProvider, m);
        }
    }

    private static void EmitTriggerDefinitionReferenceConstructor(SourceWriter w, StateMachineModel m)
    {
        var machineName = m.ClassName;

        // Static classes cannot have instance constructors; everything else uses a private ctor so the machine type
        // is not instantiable from user code while still referencing trigger parameters.
        if (m.IsStaticClass)
        {
            w.WriteLine($"static {machineName}()");
        }
        else
        {
            w.WriteLine($"private {machineName}()");
        }

        using (w.Block())
        {
            w.WriteLine("#nullable disable");
            foreach (var t in m.Triggers)
            {
                w.Write(t.Name);
                w.Write("(");
                for (var i = 0; i < t.Parameters.Count; i++)
                {
                    if (i > 0)
                    {
                        w.Write(", ");
                    }

                    w.Write("default");
                }

                w.WriteLine(");");
            }

            w.WriteLine("#nullable enable");
        }
    }

    private static RegionNode BuildRegionTree(StateMachineModel m)
    {
        var root = new RegionNode(string.Empty);
        foreach (var s in m.States)
        {
            var node = root;
            if (!string.IsNullOrEmpty(s.RegionPath))
            {
                foreach (var seg in s.RegionPath.Split('.'))
                {
                    if (!node.Children.TryGetValue(seg, out var next))
                    {
                        next = new RegionNode(seg);
                        node.Children[seg] = next;
                    }
                    node = next;
                }
            }

            node.States.Add(s);
        }

        return root;
    }

    private static void EmitRegionRegistrars(SourceWriter w, string context, string serviceProvider, StateMachineModel m)
    {
        var root = BuildRegionTree(m);
        foreach (var top in root.Children.Values)
        {
            w.WriteBlankLine();
            EmitRegionClass(w, context, serviceProvider, top);
        }
    }

    private static void EmitRegionClass(SourceWriter w, string context, string serviceProvider, RegionNode node)
    {
        w.WriteLine($"partial class {node.Name}");
        using (w.Block())
        {
            w.WriteLine(
                $"internal static void __Register(global::Nalu.SharpState.InternalEnumMap<State, global::Nalu.SharpState.IStateConfiguration<{context}, {serviceProvider}, State, Trigger, IActor>> map)");
            using (w.Block())
            {
                foreach (var s in node.States)
                {
                    EmitStateRegistration(w, s);
                }

                foreach (var child in node.Children.Values)
                {
                    w.WriteLine($"{child.Name}.__Register(map);");
                }
            }

            foreach (var child in node.Children.Values)
            {
                w.WriteBlankLine();
                EmitRegionClass(w, context, serviceProvider, child);
            }
        }
    }

    private static void EmitStateRegistration(SourceWriter w, StateModel s)
    {
        using (w.Block())
        {
            w.WriteLine($"var c = (GeneratedStateConfigurator){s.Name};");
            if (s.ParentState is not null)
            {
                w.WriteLine($"c.ApplyParent(State.{s.ParentState});");
            }
            if (s.InitialChildState is not null)
            {
                w.WriteLine($"c.ApplyInitialChild(State.{s.InitialChildState});");
            }
            w.WriteLine($"map[State.{s.Name}] = c;");
        }
    }

    private sealed class RegionNode
    {
        public RegionNode(string name)
        {
            Name = name;
        }

        public string Name { get; }
        public SortedDictionary<string, RegionNode> Children { get; } = new(StringComparer.Ordinal);
        public List<StateModel> States { get; } = new();
    }

    private static void EmitStateEnum(SourceWriter w, StateMachineModel m)
    {
        w.WriteLine("public enum State");
        using (w.Block())
        {
            foreach (var s in m.States)
            {
                EmitInheritdoc(w, s.DocumentationCommentId);
                w.WriteLine($"{s.Name},");
            }
        }
    }

    private static void EmitTriggerEnum(SourceWriter w, StateMachineModel m)
    {
        w.WriteLine("public enum Trigger");
        using (w.Block())
        {
            foreach (var t in m.Triggers)
            {
                EmitInheritdoc(w, t.DocumentationCommentId);
                w.WriteLine($"{t.Name},");
            }
        }
    }

    private static void EmitConfigurationInterface(SourceWriter w, string context, string serviceProvider)
    {
        w.WriteLine($"protected interface IStateConfiguration : global::Nalu.SharpState.IStateConfiguration<{context}, {serviceProvider}, State, Trigger, IActor>");
        using (w.Block())
        { }
    }

    private static void EmitConfiguratorInterface(SourceWriter w, string context, string serviceProvider, StateMachineModel m)
    {
        w.WriteLine("protected interface IStateConfigurator : IStateConfiguration");
        using (w.Block())
        {
            EmitWhenEnteringDocs(w, context, serviceProvider);
            w.WriteLine($"IStateConfigurator WhenEntering(Action<{context}> action);");
            w.WriteBlankLine();
            EmitWhenExitingDocs(w, context, serviceProvider);
            w.WriteLine($"IStateConfigurator WhenExiting(Action<{context}> action);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitConfiguratorTriggerDocs(w, context, serviceProvider, t);
                w.WriteLine($"IStateConfigurator On{t.Name}(Action<{BuilderInterfaceType(context, serviceProvider, t)}> configure);");
            }
        }
    }

    private static void EmitActorInterface(SourceWriter w, string context, string serviceProvider, StateMachineModel m)
    {
        var machineTypeCref = ToDocCref(MachineTypeCref(m));
        w.WriteLine("/// <summary>");
        w.WriteLine($"/// <see cref=\"{machineTypeCref}\"/> runtime actor.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <remarks>");
        w.WriteLine($"/// The machine's service provider type argument is <c>{serviceProvider}</c>.");
        w.WriteLine($"/// Use the generated <c>CreateActor</c> or <c>CreateActorWithState</c> overloads with an <see cref=\"global::Nalu.SharpState.IStateMachineServiceProviderResolver{{T}}\"/> implementation (instantiated as <c>IStateMachineServiceProviderResolver&lt;{serviceProvider}&gt;</c>) for synchronous transitions and scoped providers for <c>ReactAsync</c>.");
        w.WriteLine("/// </remarks>");
        w.WriteLine("public interface IActor");
        using (w.Block())
        {
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Gets the current leaf <see cref=\"State\"/>.");
            w.WriteLine("/// </summary>");
            w.WriteLine("State CurrentState { get; }");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Gets the shared context passed to guards, actions, and reactions.");
            w.WriteLine("/// </summary>");
            w.WriteLine($"{context} Context {{ get; }}");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Gets or sets the callback invoked when a trigger has no matching transition.");
            w.WriteLine("/// </summary>");
            w.WriteLine("global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled { get; set; }");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Raised after a transition commits and changes the current state.");
            w.WriteLine("/// </summary>");
            w.WriteLine("event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged;");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Raised when a background reaction scheduled by <c>ReactAsync(...)</c> fails.");
            w.WriteLine("/// </summary>");
            w.WriteLine("event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed;");
            w.WriteBlankLine();
            w.WriteLine("/// <summary>");
            w.WriteLine("/// Determines whether the current leaf equals <paramref name=\"state\"/> or is contained by it.");
            w.WriteLine("/// </summary>");
            w.WriteLine("/// <param name=\"state\">The state to test against the current hierarchy.</param>");
            w.WriteLine("/// <returns><c>true</c> when the actor is currently in <paramref name=\"state\"/>; otherwise <c>false</c>.</returns>");
            w.WriteLine("bool IsIn(State state);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitActorInterfaceCanTriggerMethod(w, t);
                w.WriteBlankLine();
                EmitActorInterfaceTriggerMethod(w, t);
            }
        }
    }

    private static void EmitCreateActorFactoryDelegates(SourceWriter w, string context, string serviceProvider)
    {
        EmitCreateActorWithStateFactoryDelegate(w, context, serviceProvider);
        w.WriteBlankLine();
        EmitCreateActorFactoryDelegate(w, context, serviceProvider);
    }

    private static void EmitCreateActorWithStateFactoryDelegate(SourceWriter w, string context, string serviceProvider)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Factory delegate that creates a new <see cref=\"IActor\"/> at a given <see cref=\"State\"/>, bound to this generated state machine definition.");
        w.WriteLine("/// Useful for dependency injection and unit tests.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> passed to guards, actions, and reactions.</param>");
        w.WriteLine($"/// <param name=\"serviceProviderResolver\">Resolver used for <see cref=\"global::Nalu.SharpState.IStateMachineServiceProviderResolver{{T}}.GetServiceProvider\"/> during transitions and scoped providers for <c>ReactAsync</c>.</param>");
        w.WriteLine("/// <param name=\"state\">The starting state. Composite states resolve to their initial leaf.</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance.</returns>");
        w.WriteLine($"public delegate IActor CreateActorWithStateFactory({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver<{serviceProvider}> serviceProviderResolver, State state);");
    }

    private static void EmitCreateActorFactoryDelegate(SourceWriter w, string context, string serviceProvider)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Factory delegate that creates a new <see cref=\"IActor\"/> starting at <see cref=\"GetInitialState()\"/>, bound to this generated state machine definition.");
        w.WriteLine("/// Useful for dependency injection and unit tests.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> passed to guards, actions, and reactions.</param>");
        w.WriteLine($"/// <param name=\"serviceProviderResolver\">Resolver used for <see cref=\"global::Nalu.SharpState.IStateMachineServiceProviderResolver{{T}}.GetServiceProvider\"/> during transitions and scoped providers for <c>ReactAsync</c>.</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance.</returns>");
        w.WriteLine($"public delegate IActor CreateActorFactory({context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver<{serviceProvider}> serviceProviderResolver);");
    }

    private static void EmitBuildDefinition(SourceWriter w, string context, string serviceProvider, StateMachineModel m)
    {
        w.WriteLine($"private static global::Nalu.SharpState.StateMachineDefinition<{context}, {serviceProvider}, State, Trigger, IActor> BuildDefinition()");
        using (w.Block())
        {
            w.WriteLine($"var map = new global::Nalu.SharpState.InternalEnumMap<State, global::Nalu.SharpState.IStateConfiguration<{context}, {serviceProvider}, State, Trigger, IActor>>();");

            var root = BuildRegionTree(m);
            foreach (var s in root.States)
            {
                EmitStateRegistration(w, s);
            }

            foreach (var child in root.Children.Values)
            {
                w.WriteLine($"{child.Name}.__Register(map);");
            }

            w.WriteLine($"return new global::Nalu.SharpState.StateMachineDefinition<{context}, {serviceProvider}, State, Trigger, IActor>(map);");
        }
    }

    private static void EmitActorClass(SourceWriter w, string context, string serviceProvider, StateMachineModel m)
    {
        w.WriteLine("private sealed class Actor : IActor");
        using (w.Block())
        {
            w.WriteLine($"private readonly global::Nalu.SharpState.StateMachineEngine<{context}, {serviceProvider}, State, Trigger, IActor> _engine;");
            w.WriteBlankLine();
            w.WriteLine(
                $"internal Actor(global::Nalu.SharpState.StateMachineDefinition<{context}, {serviceProvider}, State, Trigger, IActor> definition, State currentState, {context} context, global::Nalu.SharpState.IStateMachineServiceProviderResolver<{serviceProvider}> serviceProviderResolver)");
            using (w.Block())
            {
                w.WriteLine(
                    $"_engine = new global::Nalu.SharpState.StateMachineEngine<{context}, {serviceProvider}, State, Trigger, IActor>(definition, currentState, context, this, serviceProviderResolver);");
            }

            w.WriteBlankLine();
            w.WriteLine("public State CurrentState => _engine.CurrentState;");
            w.WriteBlankLine();
            w.WriteLine($"public {context} Context => _engine.Context;");
            w.WriteBlankLine();
            w.WriteLine("public global::Nalu.SharpState.UnhandledTriggerHandler<State, Trigger>? OnUnhandled");
            using (w.Block())
            {
                w.WriteLine("get => _engine.OnUnhandled;");
                w.WriteLine("set => _engine.OnUnhandled = value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public event global::Nalu.SharpState.StateChangedHandler<State, Trigger>? StateChanged");
            using (w.Block())
            {
                w.WriteLine("add => _engine.StateChanged += value;");
                w.WriteLine("remove => _engine.StateChanged -= value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public event global::Nalu.SharpState.ReactionFailedHandler<State, Trigger>? ReactionFailed");
            using (w.Block())
            {
                w.WriteLine("add => _engine.ReactionFailed += value;");
                w.WriteLine("remove => _engine.ReactionFailed -= value;");
            }

            w.WriteBlankLine();
            w.WriteLine("public bool IsIn(State state) => _engine.IsIn(state);");

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitActorCanTriggerMethod(w, t);
                w.WriteBlankLine();
                EmitActorTriggerMethod(w, t);
            }
        }
    }

    private static void EmitActorCanTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var triggerArgs = TriggerArgsFactory(t);
        w.WriteLine($"public bool Can{t.Name}({paramList}) => _engine.CanFire(Trigger.{t.Name}, {triggerArgs});");
    }

    private static void EmitActorTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var triggerArgs = TriggerArgsFactory(t);
        w.WriteLine($"public void {t.Name}({paramList}) => _engine.Fire(Trigger.{t.Name}, {triggerArgs});");
    }

    private static void EmitGeneratedConfigurator(SourceWriter w, string context, string serviceProvider, StateMachineModel m)
    {
        w.WriteLine(
            $"private sealed class GeneratedStateConfigurator : global::Nalu.SharpState.StateConfigurator<{context}, {serviceProvider}, State, Trigger, IActor>, IStateConfigurator");
        using (w.Block())
        {
            w.WriteLine("internal void ApplyParent(State parent) => SetParent(parent);");
            w.WriteBlankLine();
            w.WriteLine("internal void ApplyInitialChild(State initial) => SetInitialChild(initial);");
            w.WriteBlankLine();

            w.WriteLine($"public IStateConfigurator WhenEntering(Action<{context}> action)");
            using (w.Block())
            {
                w.WriteLine("SetEntryAction(action);");
                w.WriteLine("return this;");
            }

            w.WriteBlankLine();
            w.WriteLine($"public IStateConfigurator WhenExiting(Action<{context}> action)");
            using (w.Block())
            {
                w.WriteLine("SetExitAction(action);");
                w.WriteLine("return this;");
            }

            foreach (var t in m.Triggers)
            {
                w.WriteBlankLine();
                EmitConfiguratorTriggerMethod(w, context, serviceProvider, t);
            }
        }
    }

    private static void EmitConfiguratorTriggerMethod(SourceWriter w, string context, string serviceProvider, TriggerModel t)
    {
        var builderType = BuilderInterfaceType(context, serviceProvider, t);
        var concreteBuilder = ConcreteBuilderType(context, serviceProvider, t);
        w.WriteLine($"public IStateConfigurator On{t.Name}(Action<{builderType}> configure)");
        using (w.Block())
        {
            w.WriteLine($"var builder = new {concreteBuilder}();");
            w.WriteLine("configure(builder);");
            w.WriteLine("builder.Validate();");
            w.WriteLine($"AddTransitions(Trigger.{t.Name}, builder.BuildTransitions());");
            w.WriteLine("return this;");
        }
    }

    private static void EmitActorInterfaceTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        if (!string.IsNullOrWhiteSpace(t.DocumentationCommentId))
        {
            EmitInheritdoc(w, t.DocumentationCommentId);
        }
        else
        {
            w.WriteLine("/// <summary>");
            w.WriteLine($"/// Fires <see cref=\"Trigger.{t.Name}\"/> from the current state.");
            w.WriteLine("/// </summary>");
            foreach (var parameter in t.Parameters)
            {
                w.WriteLine($"/// <param name=\"{parameter.Name}\">The value to pass to the trigger.</param>");
            }
        }

        w.WriteLine($"void {t.Name}({paramList});");
    }

    private static void EmitActorInterfaceCanTriggerMethod(SourceWriter w, TriggerModel t)
    {
        var paramList = string.Join(", ", t.Parameters.Select(p => $"{p.TypeDisplay} {p.Name}"));
        var actorMethodCref = ActorMethodCref(t);
        w.WriteLine("/// <summary>");
        w.WriteLine($"/// Determines whether <see cref=\"{actorMethodCref}\"/> can be invoked from the current state.");
        w.WriteLine("/// </summary>");
        foreach (var parameter in t.Parameters)
        {
            w.WriteLine($"/// <param name=\"{parameter.Name}\">The value to test with the trigger.</param>");
        }
        w.WriteLine("/// <returns><c>true</c> when a matching transition exists; otherwise <c>false</c>.</returns>");
        w.WriteLine($"bool Can{t.Name}({paramList});");
    }

    private static void EmitGetInitialStateDocs(SourceWriter w)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Gets the initial root <see cref=\"State\"/> of this generated state machine.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <returns>The initial root <see cref=\"State\"/>.</returns>");
    }

    private static void EmitCreateActorWithStateMethodDocs(SourceWriter w, string context, string serviceProvider)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Creates a new <see cref=\"IActor\"/> bound to this generated state machine definition.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> passed to guards, actions, and reactions.</param>");
        w.WriteLine($"/// <param name=\"serviceProviderResolver\">Resolver for <see cref=\"global::Nalu.SharpState.IStateMachineServiceProviderResolver{{T}}\"/> (instantiated as <c>IStateMachineServiceProviderResolver&lt;{serviceProvider}&gt;</c>).</param>");
        w.WriteLine("/// <param name=\"state\">The starting state. Composite states resolve to their initial leaf.</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance.</returns>");
    }

    private static void EmitCreateActorMethodDocs(SourceWriter w, string context, string serviceProvider)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Creates a new <see cref=\"IActor\"/> bound to this generated state machine definition.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"context\">The shared <see cref=\"{ToDocCref(context)}\"/> used to create an actor starting from <see cref=\"GetInitialState()\"/>.</param>");
        w.WriteLine($"/// <param name=\"serviceProviderResolver\">Resolver for <see cref=\"global::Nalu.SharpState.IStateMachineServiceProviderResolver{{T}}\"/> (instantiated as <c>IStateMachineServiceProviderResolver&lt;{serviceProvider}&gt;</c>).</param>");
        w.WriteLine("/// <returns>A new <see cref=\"IActor\"/> instance at the machine's initial state.</returns>");
    }

    private static void EmitToDotDocs(SourceWriter w)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Renders this generated state machine as a Graphviz DOT graph.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <returns>The DOT source representing the machine graph.</returns>");
    }

    private static void EmitToMermaidDocs(SourceWriter w)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Renders this generated state machine as a Mermaid state diagram.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <returns>The Mermaid state diagram source representing the machine graph.</returns>");
    }

    private static void EmitWhenEnteringDocs(SourceWriter w, string context, string serviceProvider)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Declares a synchronous callback to run after the machine enters this state.");
        w.WriteLine(
            $"/// See <see cref=\"{ToDocCref($"global::Nalu.SharpState.StateConfigurator<{context}, {serviceProvider}, State, Trigger, IActor>.SetEntryAction(Action<{context}>)")}\"/>.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <param name=\"action\">The callback to run after the state is entered.</param>");
        w.WriteLine("/// <returns>The same configurator for chaining.</returns>");
    }

    private static void EmitWhenExitingDocs(SourceWriter w, string context, string serviceProvider)
    {
        w.WriteLine("/// <summary>");
        w.WriteLine("/// Declares a synchronous callback to run before the machine exits this state.");
        w.WriteLine(
            $"/// See <see cref=\"{ToDocCref($"global::Nalu.SharpState.StateConfigurator<{context}, {serviceProvider}, State, Trigger, IActor>.SetExitAction(Action<{context}>)")}\"/>.");
        w.WriteLine("/// </summary>");
        w.WriteLine("/// <param name=\"action\">The callback to run before the state is exited.</param>");
        w.WriteLine("/// <returns>The same configurator for chaining.</returns>");
    }

    private static void EmitConfiguratorTriggerDocs(SourceWriter w, string context, string serviceProvider, TriggerModel t)
    {
        var actorMethodCref = ActorMethodCref(t);
        var builderCref = ToDocCref(BuilderInterfaceType(context, serviceProvider, t));
        w.WriteLine("/// <summary>");
        w.WriteLine($"/// Configures what happens when <see cref=\"{actorMethodCref}\"/> is invoked.");
        w.WriteLine("/// </summary>");
        w.WriteLine($"/// <param name=\"configure\">Configures the <see cref=\"{builderCref}\"/> used by <see cref=\"{actorMethodCref}\"/>.</param>");
        w.WriteLine("/// <returns>The same configurator for chaining.</returns>");
    }

    private static string BuilderInterfaceType(string context, string serviceProvider, TriggerModel t)
    {
        const string kind = "ISyncStateTriggerBuilder";
        if (t.Parameters.Count == 0)
        {
            return $"global::Nalu.SharpState.{kind}<{context}, {serviceProvider}, State, IActor>";
        }

        var args = string.Join(", ", t.Parameters.Select(p => p.TypeDisplay));
        return $"global::Nalu.SharpState.{kind}<{context}, {serviceProvider}, State, IActor, {args}>";
    }

    private static string ConcreteBuilderType(string context, string serviceProvider, TriggerModel t)
    {
        if (t.Parameters.Count == 0)
        {
            return $"global::Nalu.SharpState.StateTriggerBuilder<{context}, {serviceProvider}, State, IActor>";
        }

        var args = string.Join(", ", t.Parameters.Select(p => p.TypeDisplay));
        return $"global::Nalu.SharpState.StateTriggerBuilder<{context}, {serviceProvider}, State, IActor, {args}>";
    }

    private static string TriggerArgsFactory(TriggerModel t)
    {
        if (t.Parameters.Count == 0)
        {
            return "global::Nalu.SharpState.TriggerArgs.Empty";
        }

        var args = string.Join(", ", t.Parameters.Select(p => p.Name));
        return $"global::Nalu.SharpState.TriggerArgs.From({args})";
    }

    private static string ActorMethodCref(TriggerModel t)
    {
        if (t.Parameters.Count == 0)
        {
            return $"IActor.{t.Name}()";
        }

        var parameterTypes = string.Join(", ", t.Parameters.Select(p => p.TypeDisplay));
        return ToDocCref($"IActor.{t.Name}({parameterTypes})");
    }

    // XML documentation cref attributes use { } for type arguments, not C# < >.
    private static string ToDocCref(string csharpTypeOrMemberId) =>
        csharpTypeOrMemberId.Replace('<', '{').Replace('>', '}');

    private static string MachineTypeCref(StateMachineModel m)
    {
        var typePath = string.Join(".", m.ContainingTypes.Select(t => t.Name).Append(m.ClassName));
        return string.IsNullOrEmpty(m.Namespace)
            ? typePath
            : $"global::{m.Namespace}.{typePath}";
    }

    private static void EmitInheritdoc(SourceWriter w, string? documentationCommentId)
    {
        if (string.IsNullOrWhiteSpace(documentationCommentId))
        {
            return;
        }

        w.WriteLine($"/// <inheritdoc cref=\"{documentationCommentId}\"/>");
    }
}
